version: '2.3'

services:
  cluster-manager-apache-kafka:
    image: cloudopsengineer/cluster-manager-apache-kafka:2.0.0.2
    container_name: cluster-manager-apache-kafka
    hostname: cluster-manager-apache-kafka
    ports:
      - 8080:8080
    environment:
      ZK_HOSTS: zookeeper:2181
      KM_USERNAME: admin
      KM_PASSWORD: admin
    cpus: "1"
    mem_limit: "1024m"

  zookeeper:
    image: cloudopsengineer/zookeeper:2.2.0
    container_name: zookeeper
    hostname: zookeeper
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped

  broker:
    image: cloudopsengineer/kafka:2.2.0
    container_name: broker
    cpus: "1"
    mem_limit: "1024m"
    restart: unless-stopped